services:
  web:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.dev
    ports:
      - "7001:7001"
    volumes:
      - ./:/usr/src/app
      - node_modules:/usr/src/app/node_modules

volumes:
  node_modules:
