export const USER_NOT_FOUND = 'E1001_USER_NOT_FOUND';
export const EMAIL_NOT_FOUND = 'E1002_EMAIL_NOT_FOUND';
export const SESSION_NOT_FOUND = 'E1003_SESSION_NOT_FOUND';
export const VERIFICATION_CODE_NOT_FOUND = 'E1004_VERIFICATION_CODE_NOT_FOUND';

export const UNAUTHORIZED_RESOURCE = 'E2000_UNAUTHORIZED_RESOURCE';
export const INVALID_CREDENTIALS = 'E2001_INVALID_CREDENTIALS';
export const INVALID_JWT_TOKEN = 'E2002_INVALID_JWT_TOKEN';
export const INVALID_VERIFICATION_CODE = 'E2003_INVALID_VERIFICATION_CODE';

export const EMAIL_USER_CONFLICT = 'E4001_EMAIL_USER_CONFLICT';

export const ORIGIN_NOT_ALLOWED = 'E5000_ORIGIN_NOT_ALLOWED';

export const UNKNOWN_ERROR = 'E9000_UNKNOWN_ERROR';
